--- #YAML:1.0
name:                Log-Dispatch-TextTable
version:             0.031
abstract:            log events to a textual table
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Log::Dispatch:                 2
    Test::More:                    0
    Text::Table:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo Signes <rjbs@cpan.org>
